### ISSUE TITLE
remove low-performance web frameworks

### ISSUE THREAD

**Issue by smallnest** [smallnest/go-web-framework-benchmark#10]
I prepare to remove those web frameworks which performance are much lower than other frameworks in the next test. For example, possum, guava studio/web, gorilla.

**Comment by kataras** [comment]
If these frameworks are used at least by one person I think you should let them here, why they must be 'banned' from this repository?

**Comment by smallnest** [comment]
See the below image, they affects display of other web frameworks. You can't compare performance of other web frameworks because bars of low-performance frameworks are too high. This is only the reason that I want to remove them from tests

![](https://github.com/smallnest/go-web-framework-benchmark/raw/master/concurrency_latency.png)

**Comment by kataras** [comment]
It doesn't feel right to me to remove them... maybe it's better idea to just make a 'faster frameworks comparison' at the end of the existing comparisons, and run a second test from the basic's comparison 'winners' , if you didn't understand (because of my english) write below to explain it with more words :P
