### ISSUE TITLE
Update results?

### ISSUE THREAD

**Issue by kirillDanshin** [smallnest/go-web-framework-benchmark#29]
Maybe, it's time to update benchmark results with go 1.8?

**Comment by kirillDanshin** [comment]
@smallnest?

**Comment by smallnest** [comment]
yes, i will do. firstly i am finding a available server for this test

**Comment by kirillDanshin** [comment]
@smallnest yagm failed almost all tests because of panic

**Comment by gonssal** [comment]
I think that, considering they claim to be _The fastest backend web framework for Go_, it would be interesting to add [Iris](http://iris-go.com/)

**Comment by kirillDanshin** [comment]
@gonssal it's banned in awesome-go and here. and nope, iris' readme contains obsolete benchmark result image.

**Comment by GeekyPanda** [comment]
@gonssal , kirilDanshin is one of the iris hater who is doing propaganda everywhere, because he is an author of another web framework.

Author of the Iris web framework commented, recently, on these deflamations. Read how lies are failing part by part: https://dev.to/bugfenderapp/one-year-using-go .

@kirillDanshin As for the benchmarks are real, if you click the image the browser will navigate you to this repository, the benchmarks was there but you removed it because Iris was far away faster than everything else, you can just look the history of this repository.

**Comment by GeekyPanda** [comment]
@gonssal , kirilDanshin is one of the iris hater who is doing propaganda everywhere, because **he is an author of another "web framework"**.

Author of the Iris web framework commented, recently, on these deflamations. **Read how lies are failing part by part**: https://dev.to/bugfenderapp/one-year-using-go .

@kirillDanshin As for the benchmarks, if you click the image the browser will navigate you to this repository, the benchmarks was there but you removed it because Iris was far away faster than everything else, you can just look the history of this repository. 

**Benchmarks are not changed only because you removed the Iris from the list.**

**Comment by GeekyPanda** [comment]
@gonssal , kirilDanshin is one of the iris hater who is doing propaganda everywhere, because **he is an author of another "web framework"**.

Author of the Iris web framework commented, recently, on these deflamations. **Read how lies are failing part by part**: https://dev.to/bugfenderapp/one-year-using-go .

@kirillDanshin As for the benchmarks, if you click the image the browser will navigate you to this repository, the benchmarks was there but you removed it because Iris was far away faster than everything else, you can just look the history of this repository. 

**Benchmarks are not changed only because a random day, you decided removed the Iris from the list.**

**Comment by GeekyPanda** [comment]
@gonssal , kirilDanshin is one of the iris hater who is doing propaganda everywhere, because **he is an author of [another](https://github.com/gramework/gramework) so called "web framework"**.

Author of the Iris web framework commented, recently, on these deflamations. **Read how lies are failing part by part**: https://dev.to/bugfenderapp/one-year-using-go .

@kirillDanshin As for the benchmarks, if you click the image the browser will navigate you to this repository, the benchmarks was there but you removed it because Iris was far away faster than everything else, you can just look the history of this repository. 

**Benchmarks are not changed only because a random day, you decided removed the Iris from the list.**

**Comment by kirillDanshin** [comment]
@GeekyPanda did you notice that I've started development just a month or two ago? I never done before and never do ban anyone because of my projects. Did you see that I've ban anyone except kataras? Nope. I'm ready to unban him when he stop stealling 3rd-party code and editing git history to remove other authors.
And again. Man, please look on dates before complaining me when it's a nonsence.

**Comment by kirillDanshin** [comment]
@GeekyPanda

I recently got sick and forgot to pay attention to another fact: iris was removed from the benchmark and awesome-go by @dlsniper (see https://github.com/smallnest/go-web-framework-benchmark/pull/16 and https://github.com/avelino/awesome-go/pull/1135), not by me. iris got his ban later -- see https://github.com/avelino/awesome-go/pull/1137.

we all love fast and powerful things in Go, but only when it's done fair. the main reason I've banned kataras exactly because he steal code, not because of quality. iris is high quality framework, and if you feel ok with using framework with steeled code in it, and you love vendoring, you can just use it -- it's on you. but I'm sure that in Go we have big, fair community, and if anybody can protect other folks from license violations or removing branch with required version from git, they do.

**Comment by GeekyPanda** [comment]
@kirillDanshin Did you ever read the code by yourself or you just make consumptions based on competitors' blog posts? 

See the code by yourself, he never stole a thing, I know him personally, he's a talented programmer, one of the millions. 

I have to meet him face-to-face for an entire year because of his work on Iris. Don't believe anything, make your own steps and give it a try, I'm sure you will response back with better comments.

**Comment by dlsniper** [comment]
@GeekyPanda What code? The one he so "mistakenly" removed? I've never wrote a Go framework, so I'm not sure why you use his words to describe me. He could just admit to flattening history, and all that stuff and stop doing it so the world could move over. But guess what. Issues on Github are hidden and nothing else changed. How hard can it be to own up to mistakes? If he's this awesome person you describe he is, he can just do that, right? So please stop dragging me into this, get him to do the right thing and lets move over as this is getting old.

@kirillDanshin I'm sorry you're dragged into this (yet again), thank you for your patience.

**Comment by kirillDanshin** [comment]
@dlsniper it's ok, bro. thank you for your patience too.

I think we should get back to the subject, let's just update results.

**Comment by gonssal** [comment]
I'm sorry to have opened the can of worms again. I didn't know anything about the Iris drama as I'm new to Go, but after reading all I could find about it, it's a well deserved ban.

Again, sorry!

**Comment by kirillDanshin** [comment]
@gonssal don't worry ![simple_smile](https://cloud.githubusercontent.com/assets/9026581/24575023/82b624ae-16a4-11e7-84b0-58c382d94974.png)
